### ISSUE TITLE
悄悄求一个编译教程

### ISSUE THREAD

**Issue by TheAutomatic** [cnsilvan/luci-app-unblockneteasemusic#1]
大佬你好，我想在我的K3上装您的解锁网易云的插件。本想用一个带插件的固件，但是下了几个都有断流问题，最后想在自己以前用的Lean大神的固件上装一个。
我尝试了用git clone命令下载您的项目到Ubuntu 18.04 LTS上，然后cd到这个目录里，输入make，但是却没有反应。作为一个很菜的纯新手实在是上不了手，还请您指教，谢谢。

**Comment by TheAutomatic** [comment]
我好像有点明白了…这个项目是不是必须要在一个openwrt固件的源码里进行编译才行。莫非不能不编译固件，只做ipk

**Comment by TheAutomatic** [comment]
尝试了在lienol大神的lede-lean固件中编译成功，扔到/lede-lean/package/lean种，编好集成在固件里，非常好用，感谢！

**Comment by cnsilvan** [comment]
用的开心就好
