### ISSUE TITLE
ssr全局以后网易云解锁无效

### ISSUE THREAD

**Issue by WROIATE** [cnsilvan/luci-app-unblockneteasemusic#10]
查看防火墙也不知道什么原因，只有把全局换了才行，请问作者知道原因吗

**Comment by cnsilvan** [comment]
全局的意思就是全部转发给另外的服务器啊。

**Comment by WROIATE** [comment]
> 全局的意思就是全部转发给另外的服务器啊。

但是按照防火墙规则的话网易解锁是在ssr前面的，不应该是先匹配网易云解锁规则，然后再由ssr转发吗，而现在的情况是直接被ssr转发了，不通过网易云

**Comment by cnsilvan** [comment]
去原作者那里提问吧。ssrplus插件代码量不少，没时间看。
这个是原作者回答过一次的[issue](https://github.com/coolsnowwolf/lede/issues/3550)
