### ISSUE TITLE
求大神给指点迷津

### ISSUE THREAD

**Issue by meiMingle** [cnsilvan/luci-app-unblockneteasemusic#13]
小白我一路摸索终于参照project-openwrt/luci-app-unblockneteasemusic里面的说明成功编译出了ipk文件。安装到openwrt里面之后却没能成功运行 ，配置及日志如下。好像说是找不到UnblockNeteaseMusic文件夹，可是小白并不知道这个文件夹应该创建在什么位置。请大神指点指点，如果大神有空的话写个稍微详细的使用说明就更好了。在此替所有小白玩家先谢谢您的辛勤付出

> create certificate...
Generating RSA private key, 2048 bit long modulus (2 primes)
..+++++
...............................................................................................................+++++
e is 65537 (0x010001)
Generating RSA private key, 2048 bit long modulus (2 primes)
..........+++++
..+++++
e is 65537 (0x010001)
Signature ok
subject=C = CN, L = Hangzhou, O = "NetEase (Hangzhou) Network Co., Ltd", OU = IT Dept., CN = *.music.163.com
Getting CA Private Key
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:06:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:07:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:08:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:09:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:10:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:11:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:12:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:13:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:14:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:15:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:16:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:17:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:18:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:19:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:20:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:21:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:22:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:23:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:24:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
Thu, 12 Mar 2020 12:25:00 +0800 尝试重启应用...
nohup: failed to run command ‘UnblockNeteaseMusic’: No such file or directory
![image](https://user-images.githubusercontent.com/39942874/76487418-56d8b400-645d-11ea-99c6-18d0800e4e0d.png)

**Comment by cnsilvan** [comment]
两个ipk，一个luci，一个UnblockNeteaseMusic，都需要安装

**Comment by meiMingle** [comment]
UnblockNeteaseMusic 编译方式和 luci 一样的吗？

**Comment by meiMingle** [comment]
UnblockNeteaseMusic 应该怎么安装呢？

**Comment by meiMingle** [comment]
已经在其他issue里面找到方法，再次感谢大神的辛勤付出

**Comment by meiMingle** [comment]
把UnblockNeteaseMusic 文件放到/usr/bin 目录下 ，然后chmod +x 授予可执行权限
