### ISSUE TITLE
openwrt 19.07.2编译失败

### ISSUE THREAD

**Issue by onlyJinx** [cnsilvan/luci-app-unblockneteasemusic#16]
大佬,我用官方SDK编译失败, 能不能帮我看下是哪里出问题了? 谢谢.

![批注 2020-03-21 155421](https://user-images.githubusercontent.com/21324835/77222247-8b9ae880-6b8c-11ea-9d13-b3d5ce6473e5.jpg)
![批注 2020-03-21 155451](https://user-images.githubusercontent.com/21324835/77222248-8dfd4280-6b8c-11ea-8f4b-09fa7a3b47ee.jpg)

**Comment by lphgor** [comment]
官方openwrt 19.07.2的tools里面缺少upx
https://github.com/cnsilvan/luci-app-unblockneteasemusic/blob/c2c68a87becdcda56e575a1609c4dd954f859f52/UnblockNeteaseMusic/Makefile#L51

**Comment by onlyJinx** [comment]
thx
