### ISSUE TITLE
VIP曲目未能解锁

### ISSUE THREAD

**Issue by zwillhill** [cnsilvan/luci-app-unblockneteasemusic#2]
希望能更新啊，谢谢

**Comment by cnsilvan** [comment]
[unblockneteasemusic](https://github.com/cnsilvan/UnblockNeteaseMusic) 目标是解锁灰色歌曲，而不是破解vip权限。

**Comment by zwillhill** [comment]
已解决，客户端的问题。回退到旧版本就OK了。
