### ISSUE TITLE
不知可否考虑与L大源码共存？

### ISSUE THREAD

**Issue by ZeaKyX** [cnsilvan/luci-app-unblockneteasemusic#20]
Lean 的 [UnblockNeteaseMusicGo](https://github.com/coolsnowwolf/lede/blob/master/package/lean/UnblockNeteaseMusicGo/Makefile) 安装目录和文件名与大佬的作品都是一样的，应该改个包名就可以了（如果改包名不妥请轻喷）
既然 workflow 都用的是 Lean 源码编译，能不能考虑共存呢 Orz

**Comment by cnsilvan** [comment]
> Lean 的 [UnblockNeteaseMusicGo](https://github.com/coolsnowwolf/lede/blob/master/package/lean/UnblockNeteaseMusicGo/Makefile) 安装目录和文件名与大佬的作品都是一样的，应该改个包名就可以了（如果改包名不妥请轻喷）
> 既然 workflow 都用的是 Lean 源码编译，能不能考虑共存呢 Orz

当初做这个luci的时候还没有其他luci适配golang，所以我就做着玩，想格外定制一些东西，不那么考虑统一性。既然你都用了lean的luci了，为什么不继续使用呢，自我感觉lean的插件比我这个优秀很多。我是做移动app开发的，在openwrt上，我是菜鸟。
