### ISSUE TITLE
x86的19.07.4在luci界面保存应用不生效。

### ISSUE THREAD

**Issue by liangchaofu** [cnsilvan/luci-app-unblockneteasemusic#21]
x86自编译的19.07.4，没修改其它选项，只添加了出国软件生成的固件。在luci界面保存应用不生效。要ssh进去手动执行才能运行，每次修改设置保存应用都不行，一定要ssh进去路由手动执行restart设置才会生效。

**Comment by cnsilvan** [comment]
检查一下日志

**Comment by liangchaofu** [comment]
日志没有报错，就是安装时有几个uci not find报错。

**Comment by cnsilvan** [comment]
> 日志没有报错，就是安装时有几个uci not find报错。

开启ipv6没？

**Comment by liangchaofu** [comment]
ipv6的都关了，用不上！！！

**Comment by lphgor** [comment]
在“高级设定”页面保存一下试试。
有些选项在config文件里没有默认值，尤其是“搜索结果限制”这一项，缺失会无法启动。
@cnsilvan 把“高级设定”独立出来以后，在“基本设定”保存，“高级设定”的选项不会生效。需要更新[/etc/config/unblockneteasemusic](https://github.com/cnsilvan/luci-app-unblockneteasemusic/blob/master/luci-app-unblockneteasemusic/root/etc/config/unblockneteasemusic) 了。

不过楼主手动能执行有点奇怪，可能还有其他问题。

**Comment by liangchaofu** [comment]
就是安装成功后，下面跟着几条就写着uci not found

**Comment by cnsilvan** [comment]
> 在“高级设定”页面保存一下试试。
> 有些选项在config文件里没有默认值，尤其是“搜索结果限制”这一项，缺失会无法启动。
> @cnsilvan 把“高级设定”独立出来以后，在“基本设定”保存，“高级设定”的选项不会生效。需要更新[/etc/config/unblockneteasemusic](https://github.com/cnsilvan/luci-app-unblockneteasemusic/blob/master/luci-app-unblockneteasemusic/root/etc/config/unblockneteasemusic) 了。
> 
> 不过楼主手动能执行有点奇怪，可能还有其他问题。

谢谢你，配置加了默认了，忘记验证‘搜索结果限制’参数了。@liangchaofu  你通过高级设置里面保存再试一下呢。
