### ISSUE TITLE
用官方主线源码加进编译，pc和安卓都无法解锁！

### ISSUE THREAD

**Issue by snakwu** [cnsilvan/luci-app-unblockneteasemusic#24]
主机名
OpenWrt
型号
Microsoft Corporation Virtual Machine
架构
Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
固件版本
OpenWrt SNAPSHOT r14698-f422488337 / LuCI Master git-20.280.41447-12e50de
内核版本
5.4.70

**Comment by snakwu** [comment]
clientlog3.music.163.com on 127.0.0.1:53: no such host

**Comment by cnsilvan** [comment]
@snakwu  上传一下插件的所有日志。

**Comment by snakwu** [comment]
Thu, 15 Oct 2020 23:11:51 +0800 # Start UnblockNeteaseMusic
Thu, 15 Oct 2020 23:11:51 +0800 # UnblockNeteaseMusic Golang Version (http:5200, https:5201)
--
		
--
2020/10/15 15:14:37 http.Client.Do fail:Post "http://clientlog3.music.163.com/api/clientlog/upload?oc=": dial tcp: lookup clientlog3.music.163.com on 127.0.0.1:53: no such host
2020/10/15 15:14:38 http.Client.Do fail:Post "http://clientlog3.music.163.com/api/clientlog/upload?oc=00B8A8C40D3F01C7733846349310E1139E3D76C1EFD097D7AE6B71C09B7D38C066002199E69A246D05948C7B6BB06682D496B1C8D68B00473DC583F56B41F13F72CC544BA3E60CA711D83ADDCD3AF33F15937D0FF0606F40E8E8

**Comment by snakwu** [comment]
@好的，我编译一个给你日志，因为之前用你的整套，pc和安卓都无法解锁，然后换了lean的，安卓仍然无法解锁，但起码可解锁pc的

**Comment by snakwu** [comment]
> @snakwu  上传一下插件的所有日志。

**Comment by snakwu** [comment]
@cnsilvan
[Uploading unblockneteasemusic.log…]()

**Comment by cnsilvan** [comment]
后续如果有人再反应，我有空再来编译官方包尝试。目前没时间。
