### ISSUE TITLE
两个问题咨询一下

### ISSUE THREAD

**Issue by qin9125** [cnsilvan/luci-app-unblockneteasemusic#26]
感谢大佬付出码代码出插件，原来你也玩黑苹果，有两个疑问问一下第一个tmp文件夹unblockneteasemusic.log日志文件会一直变大吗？我是koolshare固件在在luci界面日志点复位没反应，第二个问题openclash-开启fake-ip模式，解锁一会就会失效有办法没？谢谢

**Comment by cnsilvan** [comment]
> 感谢大佬付出码代码出插件，原来你也玩黑苹果，有两个疑问问一下第一个tmp文件夹unblockneteasemusic.log日志文件会一直变大吗？我是koolshare固件在在luci界面日志点复位没反应，第二个问题openclash-开启fake-ip模式，解锁一会就会失效有办法没？谢谢

1.不会，超多一定大小会重置
2.没研究过，你可以问问openclash的作者
3.黑果纯爱好，等arm兼容性够用后，可能不再使用了。
