### ISSUE TITLE
L大最新源码编译后无法启动

### ISSUE THREAD

**Issue by SacredOath** [cnsilvan/luci-app-unblockneteasemusic#3]
Thu Feb 13 18:36:35 2020 cron.info crond[1837]: USER root pid 7782 cmd /usr/share/UnblockNeteaseMusic/log_check.sh
Thu Feb 13 18:37:59 2020 daemon.err uhttpd[2123]: uci: Entry not found
Thu Feb 13 18:37:59 2020 daemon.err uhttpd[2123]: env: can't execute '/etc/init.d/unblockneteasemusic': Permission denied
Thu Feb 13 18:38:03 2020 daemon.err uhttpd[2123]: uci: Entry not found
Thu Feb 13 18:38:03 2020 daemon.err uhttpd[2123]: env: can't execute '/etc/init.d/unblockneteasemusic': Permission denied
Thu Feb 13 18:38:03 2020 daemon.err uhttpd[2123]: env: can't execute '/etc/init.d/unblockneteasemusic': Permission denied
Thu Feb 13 18:38:25 2020 authpriv.info dropbear[14126]: Child connection from 192.168.2.115:64473
Thu Feb 13 18:38:25 2020 authpriv.notice dropbear[14126]: Password auth succeeded for 'root' from 192.168.2.115:64473
Thu Feb 13 18:40:00 2020 cron.info crond[1837]: USER root pid 19150 cmd /usr/share/UnblockNeteaseMusic/log_check.sh

**Comment by SacredOath** [comment]
我打开/usr/share/UnblockNeteaseMusic看下了
没有生成各种证书

**Comment by cnsilvan** [comment]
权限问题，检查是否编译正确。如果还有人反应，我在看看。最近实在没空。

**Comment by tty228** [comment]
建议 make clean 清除缓存
如果同样的设备可以运行的话

**Comment by SacredOath** [comment]
> 建议 make clean 清除缓存
> 如果同样的设备可以运行的话

设备K3,尝试过以下操作
先把L大自带的luci-app-unblockmusic和UnblockNeteaseMusic删除
1.在原来基础上添加, make menuconfig 之后直接编译,无法运行
2.make clean之后make menuconfig,无法运行
3.把源码全部删除，重新git clone之后先把自带的luci-app-unblockmusic和UnblockNeteaseMusic删除，然后编译,无法运行
4.把ubuntu18虚拟机删了，重新安装虚拟机，重复3，无法运行

**Comment by tty228** [comment]
L大自带的 luci-app-unblockmusic 那个应该是 note 版本的，不影响吧

我也是 K3，内核 4.19.101
第一次编译也是无法运行，但是论坛明明很多可以运行的例子（虽然大部分是 4.14 内核）
当时证书应该是生成了，点下载是有东西的，但是日志只有刷机第一次会出现几行，之后再也没有了

除了 网易云插件 无法运行之外，系统还很不稳定，然后排查了很久，一气之下干脆重装虚拟机，刚好把 ubuntu18.04.3 换成 ubuntu-18.04.3，还有装到固态上

然后就可以运行了
两次装的软件都是一样的，排除冲突可能
我这个应该是缓存的锅
-----
你这个就不知道原因了
试过不保留设置更新吗，或者 make menuconfig 重新选插件，有的 Makefile 编译后再取消，依赖没有取消，可能会造成一些问题

**Comment by SacredOath** [comment]
> L大自带的 luci-app-unblockmusic 那个应该是 note 版本的，不影响吧
> 
> 我也是 K3，内核 4.19.101
> 第一次编译也是无法运行，但是论坛明明很多可以运行的例子（虽然大部分是 4.14 内核）
> 当时证书应该是生成了，点下载是有东西的，但是日志只有刷机第一次会出现几行，之后再也没有了
> 
> 除了 网易云插件 无法运行之外，系统还很不稳定，然后排查了很久，一气之下干脆重装虚拟机，刚好把 ubuntu18.04.3 换成 ubuntu-18.04.3，还有装到固态上
> 
> 然后就可以运行了
> 两次装的软件都是一样的，排除冲突可能
> 我这个应该是缓存的锅
> 
> 你这个就不知道原因了
> 试过不保留设置更新吗，或者 make menuconfig 重新选插件，有的 Makefile 编译后再取消，依赖没有取消，可能会造成一些问题

我每次换固件都是不保留配置更新,我也很头痛啊

**Comment by SacredOath** [comment]
> L大自带的 luci-app-unblockmusic 那个应该是 note 版本的，不影响吧
> 
> 我也是 K3，内核 4.19.101
> 第一次编译也是无法运行，但是论坛明明很多可以运行的例子（虽然大部分是 4.14 内核）
> 当时证书应该是生成了，点下载是有东西的，但是日志只有刷机第一次会出现几行，之后再也没有了
> 
> 除了 网易云插件 无法运行之外，系统还很不稳定，然后排查了很久，一气之下干脆重装虚拟机，刚好把 ubuntu18.04.3 换成 ubuntu-18.04.3，还有装到固态上
> 
> 然后就可以运行了
> 两次装的软件都是一样的，排除冲突可能
> 我这个应该是缓存的锅
> 
> 你这个就不知道原因了
> 试过不保留设置更新吗，或者 make menuconfig 重新选插件，有的 Makefile 编译后再取消，依赖没有取消，可能会造成一些问题

请问你编译成功的源码是哪个版本的,分享一下

**Comment by tty228** [comment]
create certificate...
Generating RSA private key, 2048 bit long modulus (2 primes)
..........................................................................................................................................+++++
......................+++++
e is 65537 (0x010001)
Generating RSA private key, 2048 bit long modulus (2 primes)
...+++++
................................................................................................+++++
e is 65537 (0x010001)
Signature ok
subject=C = CN, L = Hangzhou, O = "NetEase (Hangzhou) Network Co., Ltd", OU = IT Dept., CN = *.music.163.com
Getting CA Private Key

		##       ##         ##        ##   ##       ##       ## ##     ## ## ##      ## ## 
		##       ##       ## ##     ## ##  ##       ##    ##      ##      ##      ##      ##
		##       ##      ##  ##    ##  ##  ##       ##   ##               ##     ##
		##       ##     ##   ##   ##   ##  ##       ##    ## ## ##        ##     ##
		##       ##    ##    ##  ##    ##  ##       ##            ##      ##     ## 
		##       ##   ##     ## ##     ##  ##       ##  ##        ##      ##      ##      ##
		## ## ## ##  ##      ####      ##  ## ## ## ##   ## ## ##      ## ## ##    ## ## ##
		
                       0.1.3  by cnsilvan（https://github.com/cnsilvan/UnblockNeteaseMusic） 

--------------------Config--------------------
port= 5210
tlsPort= 5211
source= kuwo:migu
certFile= /usr/share/UnblockNeteaseMusic/server.crt
keyFile= /usr/share/UnblockNeteaseMusic/server.key
mode= 0
-------------------Init Host-------------------
HostDomain: map[interface.music.163.com:115.236.118.33 music.163.com:59.111.181.35]
-------------------Init Proxy-------------------
starting Server  0.0.0.0:5210
starting TLS Server  0.0.0.0:5211


这个是运行成功的完整日志
LUCI_DEPENDS:=+bash +busybox +coreutils-nohup +curl +dnsmasq-full +ipset +UnblockNeteaseMusic
PKG_BUILD_DEPENDS:=golang/host

其他依赖应该要内核支持，就不上传了

[unblock.zip](https://github.com/cnsilvan/luci-app-unblockneteasemusic/files/4209475/unblock.zip)

**Comment by SacredOath** [comment]
> create certificate...
> Generating RSA private key, 2048 bit long modulus (2 primes)
> ..........................................................................................................................................+++++
> ......................+++++
> e is 65537 (0x010001)
> Generating RSA private key, 2048 bit long modulus (2 primes)
> ...+++++
> ................................................................................................+++++
> e is 65537 (0x010001)
> Signature ok
> subject=C = CN, L = Hangzhou, O = "NetEase (Hangzhou) Network Co., Ltd", OU = IT Dept., CN = *.music.163.com
> Getting CA Private Key
> 
> ```
> 	##       ##         ##        ##   ##       ##       ## ##     ## ## ##      ## ## 
> 	##       ##       ## ##     ## ##  ##       ##    ##      ##      ##      ##      ##
> 	##       ##      ##  ##    ##  ##  ##       ##   ##               ##     ##
> 	##       ##     ##   ##   ##   ##  ##       ##    ## ## ##        ##     ##
> 	##       ##    ##    ##  ##    ##  ##       ##            ##      ##     ## 
> 	##       ##   ##     ## ##     ##  ##       ##  ##        ##      ##      ##      ##
> 	## ## ## ##  ##      ####      ##  ## ## ## ##   ## ## ##      ## ## ##    ## ## ##
> 	
>                    0.1.3  by cnsilvan（https://github.com/cnsilvan/UnblockNeteaseMusic） 
> ```
> 
> --------------------Config--------------------
> port= 5210
> tlsPort= 5211
> source= kuwo:migu
> certFile= /usr/share/UnblockNeteaseMusic/server.crt
> keyFile= /usr/share/UnblockNeteaseMusic/server.key
> mode= 0
> -------------------Init Host-------------------
> HostDomain: map[interface.music.163.com:115.236.118.33 music.163.com:59.111.181.35]
> -------------------Init Proxy-------------------
> starting Server 0.0.0.0:5210
> starting TLS Server 0.0.0.0:5211
> 
> 这个是运行成功的完整日志
> LUCI_DEPENDS:=+bash +busybox +coreutils-nohup +curl +dnsmasq-full +ipset +UnblockNeteaseMusic
> PKG_BUILD_DEPENDS:=golang/host
> 
> 其他依赖应该要内核支持，就不上传了
> 
> [unblock.zip](https://github.com/cnsilvan/luci-app-unblockneteasemusic/files/4209475/unblock.zip)

已解决,大概清楚了
要先把L大自带的UnblockNeteaseMusic删除才能./scripts/feeds update -a

**Comment by SacredOath** [comment]
刚刚测试过了,如果使用git pull同步L大的源码,一样会失效
同步之前必须得把luci-app-unblockneteasemusic文件夹删除
