### ISSUE TITLE
纯小白

### ISSUE THREAD

**Issue by SuernWU** [cnsilvan/luci-app-unblockneteasemusic#4]
怎么能下载ipk……

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by zwillhill** [comment]
下别人弄好的固件，或者学着自己编译

**Comment by cnsilvan** [comment]
基础库在不同架构编译均不同，学着自己编译或者用别人的固件。
