### ISSUE TITLE
请教下Ubuntu的neteasemusic怎么劫持

### ISSUE THREAD

**Issue by zwillhill** [cnsilvan/luci-app-unblockneteasemusic#5]
cp CA.crt /usr/share/ca-certificates/x-net.crt

拷贝证书到/usr/share/ca-certificates/下

sudo chmod a+r /usr/share/ca-certificates/x-net.crt

修改权限

sudo dpkg-reconfigure ca-certificates 

安装证书
————————————————
按照上面操作安装了证书劫持无效，显示网络无法连接，Ubuntu版本18.04，Neteasemusic客户端版本1.2，chrome网页版显示证书错误，忽略后也是无法解锁

**Comment by cnsilvan** [comment]
Ubuntu 使用 [UnblockNeteaseMusic](https://github.com/cnsilvan/UnblockNeteaseMusic)

**Comment by zwillhill** [comment]
> Ubuntu 使用 [UnblockNeteaseMusic](https://github.com/cnsilvan/UnblockNeteaseMusic/releases)
感谢回复！不过还是显示网络有问题
>                        0.1.4  by cnsilvan（https://github.com/cnsilvan/UnblockNeteaseMusic） 

--------------------Config--------------------
port= 80
tlsPort= 443
source= kuwo:kugou
certFile= /home/hanz/Downloads/UnblockNeteaseMusic-linux-amd64/server.crt
keyFile= /home/hanz/Downloads/UnblockNeteaseMusic-linux-amd64/server.key
mode= 1
-------------------Init Host-------------------
Found UnblockNetEaseMusic Line
HostDomain: map[interface.music.163.com:101.71.154.241 music.163.com:59.111.181.35]
-------------------Init Proxy-------------------
starting Server  0.0.0.0:80
starting TLS Server  0.0.0.0:443
2020/02/20 18:57:33 http2: server: error reading preface from client 127.0.0.1:40058: read tcp 127.0.0.1:443->127.0.0.1:40058: read: connection reset by peer
2020/02/20 18:57:33 http2: server: error reading preface from client 127.0.0.1:40070: read tcp 127.0.0.1:443->127.0.0.1:40070: read: connection reset by peer
2020/02/20 18:57:33 http2: server: error reading preface from client 127.0.0.1:40072: read tcp 127.0.0.1:443->127.0.0.1:40072: read: connection reset by peer
2020/02/20 18:57:33 http2: server: error reading preface from client 127.0.0.1:40076: read tcp 127.0.0.1:443->127.0.0.1:40076: read: connection reset by peer

客户端1.2.1显示网络出错，http://zitian.jb51.net:81/201906/tools/netease-cloud-music_ubuntu_jb51.deb
这个版本没有代理设置，不能设置本机ip，但是1.0的客户端Ubuntu18.04装不上。

再次感谢大佬开发K3可用的程序，win10下面用的好好的。不纠结Ubuntu

**Comment by cnsilvan** [comment]
> > Ubuntu 使用 [UnblockNeteaseMusic](https://github.com/cnsilvan/UnblockNeteaseMusic/releases)
> > 感谢回复！不过还是显示网络有问题
> > 0.1.4  by cnsilvan（[https://github.com/cnsilvan/UnblockNeteaseMusic）](https://github.com/cnsilvan/UnblockNeteaseMusic%EF%BC%89)
> 
> --------------------Config--------------------
> port= 80
> tlsPort= 443
> source= kuwo:kugou
> certFile= /home/hanz/Downloads/UnblockNeteaseMusic-linux-amd64/server.crt
> keyFile= /home/hanz/Downloads/UnblockNeteaseMusic-linux-amd64/server.key
> mode= 1
> -------------------Init Host-------------------
> Found UnblockNetEaseMusic Line
> HostDomain: map[interface.music.163.com:101.71.154.241 music.163.com:59.111.181.35]
> -------------------Init Proxy-------------------
> starting Server 0.0.0.0:80
> starting TLS Server 0.0.0.0:443
> 2020/02/20 18:57:33 http2: server: error reading preface from client 127.0.0.1:40058: read tcp 127.0.0.1:443->127.0.0.1:40058: read: connection reset by peer
> 2020/02/20 18:57:33 http2: server: error reading preface from client 127.0.0.1:40070: read tcp 127.0.0.1:443->127.0.0.1:40070: read: connection reset by peer
> 2020/02/20 18:57:33 http2: server: error reading preface from client 127.0.0.1:40072: read tcp 127.0.0.1:443->127.0.0.1:40072: read: connection reset by peer
> 2020/02/20 18:57:33 http2: server: error reading preface from client 127.0.0.1:40076: read tcp 127.0.0.1:443->127.0.0.1:40076: read: connection reset by peer
> 
> 客户端1.2.1显示网络出错，http://zitian.jb51.net:81/201906/tools/netease-cloud-music_ubuntu_jb51.deb
> 这个版本没有代理设置，不能设置本机ip，但是1.0的客户端Ubuntu18.04装不上。
> 
> 再次感谢大佬开发K3可用的程序，win10下面用的好好的。不纠结Ubuntu

使用最新版的 [UnblockNeteaseMusic](https://github.com/cnsilvan/UnblockNeteaseMusic/releases) ,linux v1.2以上在终端运行并加上 --ignore-certificate-errors 参数

**Comment by cnsilvan** [comment]
> > > Ubuntu 使用 [UnblockNeteaseMusic](https://github.com/cnsilvan/UnblockNeteaseMusic/releases)
> > > 感谢回复！不过还是显示网络有问题
> > > 0.1.4  by cnsilvan（[https://github.com/cnsilvan/UnblockNeteaseMusic）](https://github.com/cnsilvan/UnblockNeteaseMusic%EF%BC%89)
> > 
> > 
> > --------------------Config--------------------
> > port= 80
> > tlsPort= 443
> > source= kuwo:kugou
> > certFile= /home/hanz/Downloads/UnblockNeteaseMusic-linux-amd64/server.crt
> > keyFile= /home/hanz/Downloads/UnblockNeteaseMusic-linux-amd64/server.key
> > mode= 1
> > -------------------Init Host-------------------
> > Found UnblockNetEaseMusic Line
> > HostDomain: map[interface.music.163.com:101.71.154.241 music.163.com:59.111.181.35]
> > -------------------Init Proxy-------------------
> > starting Server 0.0.0.0:80
> > starting TLS Server 0.0.0.0:443
> > 2020/02/20 18:57:33 http2: server: error reading preface from client 127.0.0.1:40058: read tcp 127.0.0.1:443->127.0.0.1:40058: read: connection reset by peer
> > 2020/02/20 18:57:33 http2: server: error reading preface from client 127.0.0.1:40070: read tcp 127.0.0.1:443->127.0.0.1:40070: read: connection reset by peer
> > 2020/02/20 18:57:33 http2: server: error reading preface from client 127.0.0.1:40072: read tcp 127.0.0.1:443->127.0.0.1:40072: read: connection reset by peer
> > 2020/02/20 18:57:33 http2: server: error reading preface from client 127.0.0.1:40076: read tcp 127.0.0.1:443->127.0.0.1:40076: read: connection reset by peer
> > 客户端1.2.1显示网络出错，http://zitian.jb51.net:81/201906/tools/netease-cloud-music_ubuntu_jb51.deb
> > 这个版本没有代理设置，不能设置本机ip，但是1.0的客户端Ubuntu18.04装不上。
> > 再次感谢大佬开发K3可用的程序，win10下面用的好好的。不纠结Ubuntu
> 
> 使用最新版的 [UnblockNeteaseMusic](https://github.com/cnsilvan/UnblockNeteaseMusic/releases) ,linux v1.2以上的云音乐客户端需在终端运行并加上 --ignore-certificate-errors 参数
