### ISSUE TITLE
打开配置页面出错,请教下怎么解决!

### ISSUE THREAD

**Issue by snakwu** [cnsilvan/luci-app-unblockneteasemusic#6]
/usr/lib/lua/luci/model/cbi/unblockneteasemusic.lua:1: module 'luci.fs' not found:
	no field package.preload['luci.fs']
	no file './luci/fs.lua'
	no file '/usr/share/lua/luci/fs.lua'
	no file '/usr/share/lua/luci/fs/init.lua'
	no file '/usr/lib/lua/luci/fs.lua'
	no file '/usr/lib/lua/luci/fs/init.lua'
	no file './luci/fs.so'
	no file '/usr/lib/lua/luci/fs.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/model/cbi/unblockneteasemusic.lua:1: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1243: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:927: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:888: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:441: in function </usr/lib/lua/luci/dispatcher.lua:440>

**Comment by snakwu** [comment]
已解决!

**Comment by tty228** [comment]
你这个是怎么解决的？
我这边把 local e=require"luci.fs" 替换之后就正常了，但是同样的源码之前不会报错，重新 make menuconfig 之后感觉漏了什么东西
https://github.com/cnsilvan/luci-app-unblockneteasemusic/issues/7

**Comment by cnsilvan** [comment]
使用最新版即可

**Comment by snakwu** [comment]
把luci-lib-fs选上就可以了
