### ISSUE TITLE
我这边基于 L大 源码编译会无法进入 luci 界面

### ISSUE THREAD

**Issue by tty228** [cnsilvan/luci-app-unblockneteasemusic#7]
报错如下

/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute firstchild dispatcher target for entry '/admin/services/unblockneteasemusic'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/services/unblockneteasemusic/general'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/unblockneteasemusic.lua:1: module 'luci.fs' not found:
	no field package.preload['luci.fs']
	no file './luci/fs.lua'
	no file '/usr/share/lua/luci/fs.lua'
	no file '/usr/share/lua/luci/fs/init.lua'
	no file '/usr/lib/lua/luci/fs.lua'
	no file '/usr/lib/lua/luci/fs/init.lua'
	no file './luci/fs.so'
	no file '/usr/lib/lua/luci/fs.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

需要将 /usr/lib/lua/luci/model/cbi/unblockneteasemusic.lua 第一行
local e=require"luci.fs"
改为
local e=require "luci.sys".net

**Comment by tty228** [comment]
内核 4.19.106 
设备 斐讯k3 
固件版本	OpenWrt R20.2.15 / LuCI Master (git-20.051.42827-3e80fef)

**Comment by cnsilvan** [comment]
已解决，尝试最新版
