### ISSUE TITLE
编译成功后再luci界面无法启动UnblockNeteaseMusic 

### ISSUE THREAD

**Issue by onlyJinx** [cnsilvan/luci-app-unblockneteasemusic#8]
你好:

编译好之后安装时提示需要UnblockNeteaseMusic 这个依赖,我直接强制安装,然后装好之后我启用插件功能但是他好像没自动下载UnblockNeteaseMusic , 然后我就自己手动下载UnblockNeteaseMusic 并解压放到/usr/bin/目录下,一直启动失败,日志如下. 能帮忙看看吗?谢谢.

![image](https://user-images.githubusercontent.com/21324835/75801349-f50daf80-5db5-11ea-908a-6cc36fb790a4.png)

**Comment by cnsilvan** [comment]
手动修改hosts，删除含有music.163.com 的行

**Comment by onlyJinx** [comment]
我重新编译后可以运行了,但是启用插件之后会导致UWP网易云无网络, 关掉插件才可以用, 日志无任何报错
![image](https://user-images.githubusercontent.com/21324835/75905495-e8ee2480-5e7f-11ea-92f7-badbf5b1e78d.png)
![image](https://user-images.githubusercontent.com/21324835/75905569-09b67a00-5e80-11ea-9555-fdf6ce5cf099.png)

**Comment by cnsilvan** [comment]
uwp应用存在网络隔离，流量未转发到代理，所以没日志，先尝试非uwp吧。以后有空写教程。

**Comment by onlyJinx** [comment]
我试了桌面版的网易云也提示无网络,要关掉插件才行, 插件我是装完之后直接使用的, 没修改任何配置.有什么其他排查思路吗?

![image](https://user-images.githubusercontent.com/21324835/75997407-3e870780-5f3a-11ea-8fc8-0131107ac7be.png)

**Comment by onlyJinx** [comment]
dalao,我找到原因了,我的路由器固件只能运行那个带有softfloat尾巴的
![image](https://user-images.githubusercontent.com/21324835/75998541-efda6d00-5f3b-11ea-88c4-07f56cbe5ac8.png)
![111](https://user-images.githubusercontent.com/21324835/75998642-19939400-5f3c-11ea-9bec-c0002cca65cd.jpg)

如果下载另一个的话就会像图片那样报错,我手动下载那个带softfloat尾巴的替换bin目录下的就可以了,谢谢~~
